# Generated by Django 3.2.7 on 2021-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
