# Generated by Django 3.2.7 on 2021-09-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
    ]
