# Generated by Django 3.2.7 on 2021-09-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagTitle', models.CharField(max_length=200)),
            ],
        ),
    ]
