# Generated by Django 3.2.7 on 2021-09-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_tagdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tagContent',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tagdata',
            name='tagTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
