# Generated by Django 3.2.7 on 2021-09-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210921_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tagContent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.tagdata'),
        ),
        migrations.AlterField(
            model_name='tagdata',
            name='tagTitle',
            field=models.CharField(max_length=200),
        ),
    ]
